### ISSUE TITLE
Add python build helper

### ISSUE THREAD

**Issue by sethvargo** [chef/omnibus#262]
Right now, to execute python scripts, you have something like:

``` ruby
command "#{install_dir}/embedded/bin/python setup.py install --prefix=#{install_dir}/embedded"
```

We already have helpers for `rake` and `bundle`, so would it make sense to add a `python`  one:

``` ruby
python "setup.py install --prefix=#{install_path}/embedded"
```

This would also include `pip` too. Just like the `ruby` and `gem` helpers, it would assume the build dependency on Python (and indicate so in the documentation).

**Comment by curiositycasualty** [comment]
The bummer here is testing. A ruby environment unit or functional testing the omnibus gem has a known-good ruby. The same isn't true of Python. Functional tests are at best a "pass" when a valid python binary can't be located; and at worst, could hold up a build if a given Travis/Appveyor base image doesn't include a sane, functional python.
