### ISSUE TITLE
SmartOS can't install SVR4-style Solaris packages

### ISSUE THREAD

**Issue by juliandunn** [chef/omnibus#321]
Let me try this again in the right repo...

SmartOS does not have the old Solaris `pkgadd` commands as it uses BSD pkgsrc under the covers. Thus, our attempt to coerce it into installing a SVR4-type .pkg file is actually incorrect.

If we actually do intend to support SmartOS in the context of the platform support RFC, then we would need to build native pkgsrc packages for it. (You could `pkgtrans` the Solaris ones to it as part of CI or something, as a cheap trick.)

**Comment by bixu** [comment]
What needs to happen for us to have an auto generated chef omnibus install for SmartOS?  I would like to keep Chef as a first-class SmartOS citizen (developer momentum at $job is moving towards Ansible lately).  I'd like Chef to remain an equally valid choice :)

**Comment by bahamas10** [comment]
I would love to get chef working with omnibus on SmartOS... if there is anything I can do to help, or testing needed, etc. let me know i'm happy to help resolve this issue.

**Comment by juliandunn** [comment]
What we are in need of is some patches here. To start, you probably need to make a packager definition for SmartOS, if the toolchain is different than `solaris`, whose definition is here: https://github.com/chef/omnibus/blob/master/lib/omnibus/packagers/solaris.rb

After that, you can wire it into the [platform packager map](https://github.com/chef/omnibus/blob/master/lib/omnibus/packager.rb) and try to omnibus-build a Chef client using the [omnibus-chef](https://github.com/chef/omnibus-chef) project. Chances are, a native SmartOS build won't quite work because of Solaris conditionals, but it shouldn't be too much work to add that into the omnibus-chef project definition.

It's unlikely that Chef Software, Inc. will have paid developer resources to put into this effort, as SmartOS is not a platform used by very many customers, but we would definitely take community patches. Hopefully the foregoing is enough for those who are interested to go on!

**Comment by bahamas10** [comment]
Great, thank you for the information @juliandunn 

I'm currently attempting to run `bundle exec omnbus build chef` in `omnibus-chef` to completion without failing.  I believe this patch https://github.com/chef/dep-selector-libgecode/pull/41 will fix some (if not all) of the errors I'm currently seeing.

I do have a question regarding the package building process however.  From what I understand about packaging on SmartOS, the prefix defaults to `/opt/local`... i don't know if it is possible to install to a path outside of that directory.  However, I would imagine that this is an issue that isn't unique to SmartOS, so how does omnibus get around this?

**Comment by bixu** [comment]
@bahamas10 I've got a real need for omnibus chef on SmartOS, so if you ever want to remote pair on this stuff, let me know.  I'm in the Berlin timezone.

**Comment by juliandunn** [comment]
@bahamas10 I've never seen a packaging system enforce that packages can only be installed to a particular hierarchy. Omnibus assumes that the package will live in `/opt/chef`

**Comment by bixu** [comment]
`/opt` on SmartOS should be a fine location for the Omnibus install, as `/opt` is read/write on SmartOS.

**Comment by bahamas10** [comment]
@bixu me too.. i'm in New York timezone but would be happy to sit down and try to nail this down.

@juliandunn I believe `pkg` on freebsd has very strict rules about packages being stuck in `/usr/local` for instance.  Any package installed via that method will be under that directory for security purposes... i don't know if SmartOS is the same way.

Either way, like @bixu mentioned it's a moot point, because worst case scenario there could be a post install script to `mv /path/where/chef/was/installed /opt/chef`

**Comment by bahamas10** [comment]
Just to get an updated todo

1. get `bundle exec omnibus build chef` to work on smartos
2. add a SmartOS packager definition to this project

To expand on section 1, we need to fix the bugs that are currently stopping this from working

- ffi not compiling - https://github.com/ffi/ffi/issues/360
- dep-selector-libgecode not compiling - https://github.com/chef/dep-selector-libgecode/pull/41

If someone knows how to use those branches when running `bundle exec omnibus build chef` we can test them out and move forward.

**Comment by juliandunn** [comment]
Couple options for you to proceed:

* Modify the Gemfile temporarily in your `omnibus-chef` project to point to your own checkout of `omnibus-software` (https://github.com/chef/omnibus-chef/blob/master/Gemfile#L4) so you can hack around
* Modify software definitions for `libffi` (in `config/software`) and `dep-selector-libgecode` to patch them, change source, or whatnot

**Comment by bixu** [comment]
@juliandunn, thanks for the tips.

@bahamas10, when do you want to remote-pair on this?  thinking screenhero here - drop me an email via my GitHub profile?

**Comment by michaelcarruthers** [comment]
@bixu I am needing to have a SmartOS omnibus package, let me know if you need an extra pair of hands.

**Comment by bahamas10** [comment]
FWIW these steps can get ruby and chef compiled and installed to `/opt/chef` on SmartOS.  it's not the same as omnibus, but it does result in a self-contained chef installation https://gist.github.com/bahamas10/6a052faa8644d3d462d5
