### ISSUE TITLE
Select packager/compressor

### ISSUE THREAD

**Issue by waj** [chef/omnibus#348]
Is there any way I can force the packager and/or the compressor for a project? I'm trying to make a package that would be portable between Linux distributions and I'd like to generate a .tar.gz or use makeself instead of having .deb or .rpm packages generated.

**Comment by salsa-dev** [comment]
+1

**Comment by thommay** [comment]
We'd take a pull request that implements this, but we have no use for the feature ourselves right now so it's incredibly unlikely that we'd work on it.
