### ISSUE TITLE
Raspbian run produces archv6l .deb package, should be armhf

### ISSUE THREAD

**Issue by barnabear** [chef/omnibus#352]
File lib/omnibus/packagers/deb.rb line defines function "safe_architecture" on line 380.

In Raspian this currently returns armv6l, which is arm version 6 little endian as reported by 'uname -a'. However Raspbian expects packages to be compiled with hardware floating point support (armhf).

Hence the architecture property in the .deb file (armv6l) doesn't match that required by dpkg (armhf), so this gives an error. This can be overridden by using the --force-architecture option, but really it needs fixing at source.

Given that I knew that I was running on a Raspbian system, I just patched it locally with return 'armhf' after line 380.

It would be possible to patch this in a portable way e.g. by testing for Ohai[platform] == 'raspbian'. Nothing in the output from Ohai appears to contain "armhf".

I don't know about Pidora, since I don't use it, but it's likely the same story.

With this and issue #349 patched locally, omnibus builds the chef client on Raspbian just fine (in about 4 hours). :o)

**Comment by lamont-granquist** [comment]
closing as an old ticket getting no traction.  pi builds are very low priority.
