### ISSUE TITLE
"View on GitHub" links in documentation are broken

### ISSUE THREAD

**Issue by promisedlandt** [chef/omnibus#362]
For example, on http://rubydoc.info/github/opscode/omnibus/Omnibus/Project#dependency-instance_method, "View on GitHub" points to:
https://github.com/opscode/omnibus/blob/Omnibus/lib/omnibus/project.rb#L887
but should (I'm guessing) point to:
https://github.com/opscode/omnibus/blob/master/lib/omnibus/project.rb#L887

That's also not the correct line, making me think that the documentation is out of date anyway.

**Comment by lamont-granquist** [comment]
I have no idea how those are generated.  Looks more like a problem with rubydoc.info, but if it takes changes here to fix that PR would be accepted.
