### ISSUE TITLE
Add ability to sign Debian (.deb) packages.

### ISSUE THREAD

**Issue by kwilczynski** [chef/omnibus#402]
We already sign the _RPM_ packages and the _PKG_ files when they are built by Omnibus, and so it would be nice to sign _Debian_ (`.deb`) packages too.

**Comment by Hobbsee** [comment]
Useful links here:

http://blog.packagecloud.io/eng/2014/10/28/howto-gpg-sign-verify-deb-packages-apt-repositories/
https://purplefloyd.wordpress.com/2009/02/05/signing-deb-packages/

I've verified that following the instructions in these links, when using a omnibus-built deb, works correctly.

**Comment by Hobbsee** [comment]
There are a couple of outstanding issues:
  - debsigs isn't installed by default.  Do we rely on the user to install this, or do we add this as a dependency of omnibus somewhere?  If the latter, how is this done?
  - debsigs doesn't seem to allow you to specify a passphrase via the command line, even with what GPG normally accepts:
```
PASSPHRASE='foobar' debsigs --sign=origin -k 803709B6 /vagrant/pkg/flapjack_1.2.1~+20141218052006-v1.2.1-trusty-1_amd64.deb
```

The tests pass.  Once the passphrase issue is sorted out, I'll test-build flapjack with this, and see how it actually works.

**Comment by kwilczynski** [comment]
@Hobbsee you back look how signature is added and then do it in pure Ruby, it's trivial. This avoid dependency issues with `debsigs`, etc.

Anyway, thank you for doing this, outstanding work! :+1: :heart: :cake:

**Comment by Hobbsee** [comment]
Ah, of course!  I'll take a look.

**Comment by kwilczynski** [comment]
@Hobbsee you are a :star: :)

**Comment by yzl** [comment]
@Hobbsee The [omnibus cookbook](https://github.com/opscode-cookbooks/omnibus) should install `debsigs`.

**Comment by WarheadsSE** [comment]
Somewhat necro, I know, and apologize.
I wanted to chime in here, and let others know that GitLab has tasked me with actively adding DEB signing to Omnibus. I have work on our fork, which I will be providing as a PR here in the near future.

Thanks to all in this thread for your existing work, which I used as a basis for research and input for keeping the additions to a minimum of added cruft.

**Comment by WarheadsSE** [comment]
For those of you who may be following, I have opened #799 with the changes we have implemented at GitLab, allowing us to distribute `debsigs` signed DEB packages.

**Comment by kwilczynski** [comment]
@WarheadsSE nice work. I will have a look at the Pull Request, but I am sure it's fine 👍
