### ISSUE TITLE
Question: why does `with_standard_compiler_flags` not include `CPPFLAGS`?

### ISSUE THREAD

**Issue by krallin** [chef/omnibus#415]
I've noticed that I'm unable to build `openldap` why Omnibus without including `CPPFLAGS` in the environment, because `openldap` uses `AC_EGREP_CPP` to check for dependency compatibility, e.g. in [`build/configure.m4:1111`](http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=build/openldap.m4;h=caf8fc2aa6642b3d2ffe02f56dd0a343d4be32f5;hb=HEAD#l1111)

    dnl Check for Cyrus SASL version compatility
    AC_DEFUN([OL_SASL_COMPAT],
    [AC_CACHE_CHECK([Cyrus SASL library version], [ol_cv_sasl_compat],[
            AC_EGREP_CPP(__sasl_compat,[
    #ifdef HAVE_SASL_SASL_H
    #include <sasl/sasl.h>
    #else
    #include <sasl.h>
    #endif
    
    /* Require 2.1.15+ */
    #if SASL_VERSION_MAJOR == 2  && SASL_VERSION_MINOR > 1
            char *__sasl_compat = "2.2+ or better okay (we guess)";
    #elif SASL_VERSION_MAJOR == 2  && SASL_VERSION_MINOR == 1 \
            && SASL_VERSION_STEP >=15
            char *__sasl_compat = "2.1.15+ or better okay";
    #endif
            ],      [ol_cv_sasl_compat=yes], [ol_cv_sasl_compat=no])])
    ])

Setting `env['CPPFLAGS'] = env['CFLAGS']` does the trick, of course, but I'm curious to understand if there is a reason for omnibus to not do this by default?

Cheers,

**Comment by schisamo** [comment]
@krallin No hard reason it was not included. All the software we are building with Omnibus up to this point just hasn't needed it. /cc @lamont-granquist

**Comment by lamont-granquist** [comment]
yep, just hasn't come up yet in our internal builds

**Comment by krallin** [comment]
@schisamo Oh, OK then, thanks!  : ) 

I've noticed I actually get a lot of warnings like the following:

    configure: WARNING: bzlib.h: accepted by the compiler, rejected by the preprocessor!
    configure: WARNING: bzlib.h: proceeding with the compiler's result

Would it make sense to include `CPPFLAGS` in the standard compiler flags (considering it usually isn't a fatal issue, but sometimes is?)

**Comment by lamont-granquist** [comment]
We actually set it for ruby compiles:

https://github.com/opscode/omnibus-software/blob/12909667bfb281f65093afb15157a7eb1523b3cc/config/software/ruby.rb#L71

Putting it in the default flags would hopefully make that line go away.

**Comment by schisamo** [comment]
@krallin Want to take a stab at a PR for this feature?

**Comment by krallin** [comment]
@schisamo Sure, that sounds good. 

I'll try and do that within a few days then!

**Comment by krallin** [comment]
@schisamo ,

So, looking into this, it seems that `CLFAGS` is being used mostly for what appears to be pre-processor options (`-I` and `-D` specifically, which according to e.g. [this doc][0] are expected to be in `CPPFLAGS`) 

I guess we have two options:

  + Replace `CFLAGS` with `CPPFLAGS` for `-I` and `D`, set `CFLAGS` only when there are actual compiler options passed (i.e. on AIX, there are a few actual compiler options in `CFLAGS`). I'm concerned this will break all configs that do ` x = env['CFLAGS']`.
  + Do that, but also default `CFLAGS` (and `CXXFLAGS`) to `CPPFLAGS` (unless otherwise set, like in AIX's case). This provides backwards compatibility.
  + Merely give `CPPFLAGS` the treatment `CXXFLAGS` is currently receiving (which is to inherit `CFLAGS`'s value). This keeps things like they currently are (with preprocessor flags in `CLFAGS`), but should work anyway.

Thoughts? I guess this comes down to your stability policy (the PR itself should be pretty trivial). 

  [0]: http://www.gnu.org/software/autoconf/manual/autoconf.html#Preset-Output-Variables

**Comment by lamont-granquist** [comment]
AFAIK just defaulting CPPFLAGS to CFLAGS should be fine for what we're doing.  I wouldn't remove anything from CFLAGS unless it's identified as a problem with some compiler (and i'd be more worried about clang or xlc than gcc).

**Comment by schisamo** [comment]
This was fixed with #416.
