### ISSUE TITLE
Windows boxes

### ISSUE THREAD

**Issue by PierreRambaud** [chef/omnibus#425]
Hi,

Is there a simple way to play with windows boxes? I can't find a windows box to execute `bundle exec kitchen converge` and after play with omnibus, I try to build some with `veewee` but nothing work and there's not enought information in all documentation i could find.
Can you add add in generated kitchen yaml file a valid windows box?

Regards

**Comment by PierreRambaud** [comment]
Gentle ping!

**Comment by jdmundrawala** [comment]
We are not allowed to publish windows boxes. You can generate them with [box cutter](https://github.com/boxcutter/windows) or packer[https://github.com/joefitzgerald/packer-windows] or [bento](https://github.com/chef/bento

**Comment by PierreRambaud** [comment]
Thanks, I will have a look ;)
