### ISSUE TITLE
Omnibus packages fail to purge all gems when upgrading/uninstalling

### ISSUE THREAD

**Issue by ryancragun** [chef/omnibus#427]
Omnibus packages fail to purge user installed gems when they're deleted.  eg:

``` shell
root@cscbackup:/opt# curl chef.sh | bash -s -- -v 11.12.2
 ...
root@cscbackup:/opt# echo "chef_gem 'ridley'" > /tmp/recipe.rb
root@cscbackup:/opt# chef-apply /tmp/recipe.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * chef_gem[ridley] action install
    - install version 4.1.2 of package ridley
  * chef_gem[ridley] action install (up to date)
root@cscbackup:/opt# dpkg -r chef
(Reading database ... 100292 files and directories currently installed.)
Removing chef ...
root@cscbackup:/opt# dpkg-query -L chef
/opt
/opt/chef
/opt/chef/embedded
/opt/chef/embedded/lib
/opt/chef/embedded/lib/ruby
/opt/chef/embedded/lib/ruby/gems
/opt/chef/embedded/lib/ruby/gems/1.9.1
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems
/opt/chef/embedded/lib/ruby/gems/1.9.1/specifications
/opt/chef/embedded/lib/ruby/gems/1.9.1/cache
root@cscbackup:/opt# ls /opt/chef/embedded/lib/ruby/gems/1.9.1/gems | grep ridley
ridley-4.1.2
```

In the case of an upgrade, I now have several gems in the cache that are missing dependencies ( which were included in the base chef install but have now been purged.) 

Now lets upgrade the package. `gem` and `chef_gem` will now believe 'ridley' is installed with all of the required dependencies, but we know that is not the case.

``` shell
root@cscbackup:/opt# curl chef.sh | bash -s -- -v 11.18.0
...
root@cscbackup:/opt# chef-apply /tmp/recipe.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * chef_gem[ridley] action install (up to date)
  * chef_gem[ridley] action install (up to date)
root@cscbackup:/opt# /opt/chef/embedded/bin/gem list -i ridley
true
root@cscbackup:/opt# /opt/chef/embedded/bin/irb -r ridley
/opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:298:in `to_specs':Gem::LoadError: Could not find 'json' (>= 1.7.7) - did find: [json-1.5.5]
```

Similar problems occur with the omnibus Chef Server, a much smaller problem as user gem installs are less likely on the Chef Server than the chef-client, but a problem nonetheless.  Hence, the issue has been reported upstream.

**Comment by ryancragun** [comment]
cc @sean-horn @david-crowder

**Comment by lamont-granquist** [comment]
Is there any fix to this other than wiping the project directory on an upgrade which seems like potentially a really terrible idea to me -- particularly running rm_rf's across you chef-server just seems like you're asking for some state to accidentally wind up in that directory and then to have users angry that their upgrade blew away their critical whatever.  In chefdk, the use of `~/.chefdk` mitigates this some, but I can see users who have managed to install gems into /opt/chefdk/embedded getting upset when a point upgrade wipes all of that out as well.

I've always considered this a necessary behavior (and convenient when the gem deps do not change) and not a bug.

**Comment by ryancragun** [comment]
I think there are only two solutions: remove user installed gems on upgrade or reinstall user installed gems to ensure that all dependencies are there.  The former is my preferred solution, but the latter could be possible as a post install hook.   I also think that we could add add support for gem validation to the rubygems package provider.  Right now it believes (as it probably should) that if the gemspec is in the cache that the dependent gems are also installed.  We could make it do a gem validation and repair on gems it believes are already installed.  That'd be treating the symptom instead of the cause though.

**Comment by schisamo** [comment]
Perhaps we should stop installing stuff into the package install tree (e.g. `/opt/PROJECT`). I know with all server products we try to place any files that are installed post package install are created into `/var/opt/PROJECT`. I wonder if any gems that are installed as part of a CCR belong in a secondary location.

As @lamont-granquist suggested we could ensure gems are routed to a secondary location with some RubyGems customization like in ChefDK: 
https://github.com/chef/omnibus-chef/blob/master/config/software/rubygems-customization.rb https://github.com/chef/omnibus-chef/blob/master/files/rubygems-customization/default/operating_syst...

The gems (and their deps) would exist in this secondary location even after you re-install or upgrade the package. `/opt/PROJECT` should be treated as sacred and fully controlled by the package NOT by the end user.

**Comment by lamont-granquist** [comment]
Old gems in /var/opt/PROJECT will still cause the same issue.  Problem is that the package upgrade needs to blow away files that were chef_gem installed outside of the package manager.

You could use /var/opt/PROJECT/VERSION so that the old files would be left but the new package would go looking for gems in a different directory.

I tend to think that this needs to be the responsibility of the omnibus_updater cookbook to (configurable) rm -rf the whole directory.

**Comment by lamont-granquist** [comment]
This was done in chef/chef here:

https://github.com/chef/chef/blob/d5e12e6d2f971ef70e9d6d29331123e2701b796c/omnibus/package-scripts/chef/preinst

Not really appropriate to put that directly into omnibus.
