### ISSUE TITLE
Add support to sha1sum for software download using NetFetcher

### ISSUE THREAD

**Issue by hugosato** [chef/omnibus#454]
In my current deployed version of omnibus v4.0.0, only md5 integrity check is supported. I would like to add support for sha1, e.g.: [sqlite](https://www.sqlite.org/download.html). 

Before I start the work, any initial consideration/comment from active developers?

**Comment by stevendanna** [comment]
@hugosato Will this address your need: https://github.com/chef/omnibus/pull/440

**Comment by hugosato** [comment]
Yes, @stevendanna. Closing in favor to #440.
