### ISSUE TITLE
Question: Why with_standard_compiler_flags doesn't resolve merge conflicts with duplicate env's key?

### ISSUE THREAD

**Issue by hugosato** [chef/omnibus#455]
Scenario example: Some of Software needs both standard and custom CXXFLAGS (e.g.: -fPIC.)

Instead of hardcoding standard flags in a custom env map, could we pass a merge strategy or expect a default concatenation instead of [replacing old value with new value](https://github.com/chef/omnibus/blob/master/lib/omnibus/software.rb#L530)?

Currently, my workaround is to pass custom CXXFLAGS as command arguments to configure; while standard flags goes along env. However, this most likely will work for autoconf only but confusing for future maintainers.

**Comment by lamont-granquist** [comment]
1. omnibus should fully specify the build environment and not pass through CFLAGS from the outer shell
2. we always call with_standard_compiler_flags first in a definition so they're the defaults
3. we then override later in ruby code where you can roll your own merge strategy however you want

definitely don't understand the need for the feature.  nobody else has +1'd this or run into it.  if you can find a better example of how it doesn't work and how you can't refactor to follow the pattern we follow in omnibus-software, feel free to open a new issue and/or pull request, but right now i can't understand the need here.
