### ISSUE TITLE
Preserve hard links in FileSyncer#sync?

### ISSUE THREAD

**Issue by jacobvosmaer** [chef/omnibus#459]
We are seeing an interesting difference between the omnibus build product on our build boxes and on target systems after installing a DEB/RPM: hard links are not being preserved. When packaging Git with omnibus this seems to lead to a dramatic increase in disk use.

- FPM issue https://github.com/jordansissel/fpm/issues/365
- GitLab issue https://gitlab.com/gitlab-org/omnibus-gitlab/issues/274

On our builders, git sub-commands in libexec take up about 18MB:

```
$ ls -l /opt/gitlab/embedded/libexec/git-core/ | awk ' {total += $5 } END { print total/1024/1024 }'
259.11
$ du -sh /opt/gitlab/embedded/libexec/git-core 
18M	/opt/gitlab/embedded/libexec/git-core
```

But after installation, we are looking at 250+MB for the same directory:

```
$ du -sh /opt/gitlab/embedded/libexec/git-core/
260M	/opt/gitlab/embedded/libexec/git-core/
```

The problem is with hard links it seems, and I suspect that FileSyncer#sync is where the hard links get lost. `libexec/git-core` contains 100+ hard links to a single file. Considering how big omnibus packages can get to begin with, it might be nice if we could prevent exacerbating the situation by forgetting hard links.

**Comment by jacobvosmaer** [comment]
This is how FPM ended up fixing the problem: https://github.com/jordansissel/fpm/commit/32c6be5488ed5a193498528c23620cb1c5aa5d31

**Comment by curiositycasualty** [comment]
.jkeiser Walked me through how Chef handles this in the link/file provider. It's quite complex and ends up using a combination of a volume's serial number combined with the files "index" (https://github.com/chef/chef/blob/master/lib/chef/win32/file/info.rb#L83-L85) patched into a clone of the File class (file_class), both of which are obtained through the Win32 API.

**Comment by jacobvosmaer** [comment]
On Unix-ish systems I would guess you could use `File.stat` and track the device/inode numbers, like the FPM patch does. I have no idea if `File.stat` contains useful/trustworthy information on Windows.

**Comment by curiositycasualty** [comment]
The linux-only solution (for now) lives in https://github.com/chef/omnibus/pull/479
Preliminarily, Ruby's support for all the various Windows link-types looks extremely iffy; but we'll cross that bridge when we get to it.

**Comment by curiositycasualty** [comment]
closing has fix merged
