### ISSUE TITLE
Invalid md5sums file created by deb packager

### ISSUE THREAD

**Issue by dmlary** [chef/omnibus#462]
After installing a package created by the omnibus deb packager, the `dpkg --verify` command fails with the following error: `dpkg: error: control file 'md5sums' missing value separator`.  Looking at the metadata for the package, the md5sums file is using only a single space to separate the hash from the filename; the dpkg tool requires them be separated by two spaces.

A change should be made in resources/deb/md5sums.erb, to add the additional space.

Here's my pull request for reference: https://github.com/chef/omnibus/pull/461

**Comment by schisamo** [comment]
This was fixed in https://github.com/chef/omnibus/issues/595
