### ISSUE TITLE
Update Omnibus::BuildVersion#build_start_time to use BUILD_TIMESTAMP

### ISSUE THREAD

**Issue by schisamo** [chef/omnibus#481]
Jenkins 1.597+ changed the format of `BUILD_ID` from being a timestamp to the same value as `BUILD_NUMBER` which is an Integer. Omnibus looks for `BUILD_ID` but expects it to be in the old format of `yyyy-MM-dd_HH-mm-ss`. 

Chef Software Inc.'s workaround is to use the [Zen Timestamp plugin](https://wiki.jenkins-ci.org/display/JENKINS/ZenTimestamp+Plugin) to generate a new `BUILD_TIMESTAMP` value in the expected timestamp format. Omnibus will also be updated to look for `BUILD_TIMESTAMP` but we’ll also set `BUILD_ID` to the value of `BUILD_TIMESTAMP` for projects stuck on older versions of Omnibus.

See [JENKINS-26520](https://issues.jenkins-ci.org/browse/JENKINS-26520) for more details on the `BUILD_ID` change and it’s fallout!

**Comment by schisamo** [comment]
We'll need the code to be smart enough to prefer `BUILD_TIMESTAMP` and fall back to `BUILD_ID`. I still think it's a good idea for it to throw an exception if parsing of either one fails.

**Comment by lamont-granquist** [comment]
looks fixed
