### ISSUE TITLE
white list libgcc on Mac

### ISSUE THREAD

**Issue by ahelal** [chef/omnibus#500]
Not sure if its a bug or misconfig on my side. I am compiling python on Mac and getting `The following libraries cannot be guaranteed to be on target systems:
    --> /usr/lib/libgcc_s.1.dylib`
On Solaris and smartos the lib is in the white list.

Thank you

**Comment by schisamo** [comment]
@ahelal It seems reasonable that `libgcc` would be included in the Mac whitelist. It's in the default whitelist:
https://github.com/chef/omnibus/blob/ce9639e12b50ce5b58e63a81aa0f09f29fc95315/lib/omnibus/health_check.rb#L28

Thoughts @chef/omnibus-maintainers? We haven't had this issue in our Mac builds BUT we also don't compile/ship Python in any of our products that ship on OS X. My only worry would be a situation where your Python is being compiled with a nonstandard compiler on your build machine...e.g. you have the default Clang installed (from the Command Line Tools) and also GCC installed from Homebrew.

**Comment by sethvargo** [comment]
@schisamo that seems reasonable to me. My only concern is - what happens if the user has installed a custom GCC (perhaps via homebrew)?

**Comment by scotthain** [comment]
Seems reasonable, I'm wondering if it might be better (unless this is really widespread) to use a ```whitelist_file /libgcc_s\.so/``` in the main software def that is using this (ie the 'main' project) in this instance?

**Comment by ahelal** [comment]
My thoughts,

@schisamo I think its safe if we assume that even if a user install a custom compiler with homebrew, He will still have the system libgcc.

@scotthain Just as a note the format on mac is libgcc_s\.dylib/

**Comment by schisamo** [comment]
@ahelal Can you try adding this to your project's main software definition:

```ruby
whitelist_file /libgcc_s\.dylib/
```

**Comment by ahelal** [comment]
@schisamo for some reason that does not work. It only works if I put it in lib/omnibus/health_check.rb
I might have missed something

**Comment by lamont-granquist** [comment]
I'm reasonably certain this works for us because we use clang llvm-gcc and not actual-gcc.

Users that are compiling with actual-gcc on mac should just add it to their whitelist of their projects.
