### ISSUE TITLE
"Could not locate or access the package at the given path" on centos 6 

### ISSUE THREAD

**Issue by tristanjuricek** [chef/omnibus#511]
I'm getting the error when building an RPM on a CentOS 6 instance

                        [Packager::RPM] I | Rendering `/home/perforce/.rvm/gems/ruby-2.2.2@build/bundler/gems/omnibus-438bb3561c49/resources/rpm/spec.erb' to `/tmp/helix-web-services20150710-18415-8fn1z2/SPECS/helix-web-services-2015.1+20150710224334-1.el6.x86_64.rpm.spec'
                        [Packager::RPM] I | Creating .rpm file
    Could not locate or access the package at the given path:
    
        /var/cache/omnibus/pkg/helix-web-services-2015.1+20150710224334-1.el6.x86_64.rpm

What's strange is that CD-ing to the temp directory and running {{rpmbuild}} is working.

    cd /tmp/helix-web-services20150710-18415-8fn1z2/
    rpmbuild --buildroot=`pwd`/BUILD -ba SPECS/helix-web-services-2015.1+20150710224334-1.el6.x86_64.rpm.spec

The output looks like this:

    Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.bRGoaz
    Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.F88hbs 
    Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.VuHwcl
    Processing files: helix-web-services-2015.1+20150710224334-1.el6.x86_64
    Checking for unpackaged file(s): /usr/lib/rpm/check-files /tmp/helix-web-services20150710-18415-8fn1z2/BUILD
    Wrote: /root/rpmbuild/SRPMS/helix-web-services-2015.1+20150710224334-1.el6.src.rpm
    Wrote: /root/rpmbuild/RPMS/x86_64/helix-web-services-2015.1+20150710224334-1.el6.x86_64.rpm
    Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.Ugf2pR

(The above was run as root, but I've gotten the same results running as a normal user.) 

How is the rpm getting generated from the spec? Via `rpmbuild`? I'm fairly new to omnibus so I'm not exactly sure how the source is organized.

I'm using very recent versions of `omnibus` and `omnibus-software. 

    GIT
	  remote: git://github.com/chef/omnibus-software.git
	  revision: 2d1b0f827c0304d5e59b6da09b057f4fcbcf639e
	  specs:
	    omnibus-software (4.0.0)

	GIT
	  remote: git://github.com/chef/omnibus.git
	  revision: 438bb3561c4945110452b416448e417c42e8ba27
	  specs:
	    omnibus (4.0.0)
            .... snip....

**Comment by tristanjuricek** [comment]
This may be an issue with the local environment. I noticed that a couple of binary files installed via yum were actually empty files. 

I've since rebuilt a different VM using the `omnibus` chef cookbook on CentOS 6, and have not reproduced this issue.

**Comment by gilzellner** [comment]
this is happening to me sporadically.

**Comment by gilzellner** [comment]
building on centos7
