### ISSUE TITLE
cache operations should work with all software

### ISSUE THREAD

**Issue by thommay** [chef/omnibus#528]
As a developer, when I run `omnibus cache populate` and friends, I want all the software to be uploaded, regardless of platform and optionality.

eg:
```
dependency "vcredist" if windows?
```
should cause the `vcredist` executable to be uploaded to S3 regardless of the fact I'm running `omnibus cache populate` on a mac.

**Comment by thommay** [comment]
Plausibly it should also ensure that every listed version of `vcredist` is uploaded, not just the one that's depended on, although I understand why that's not the case.

**Comment by lamont-granquist** [comment]
So to make this:

```ruby
dependency "foo" if windows?
dependency "bar" unless windows?
```

both upload "foo" and "bar" we have to magically assert the right boolean value of `windows?`, in a context dependent way, to make the dependency get added.

i suspect we will never implement this...
