### ISSUE TITLE
Many packages using with_standard_compiler_flags are built without optimization

### ISSUE THREAD

**Issue by hwti** [chef/omnibus#590]
When looking at GitLab performance, I saw many packages were built without optimization (no -O* flag).

For example:
- https://github.com/chef/omnibus-software/blob/master/config/software/zlib.rb
- https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/config/software/git.rb

The issue is [with_standard_compiler_flags](https://github.com/chef/omnibus/blob/master/lib/omnibus/software.rb#L535) sets CFLAGS, which overwrites the default value (often -O2 -g) in many opensource packages (especially autotools based ones).

Two possible fixes:
- only set CPPFLAGS, not CFLAGS/CXXFLAGS
- add -O2 to CFLAGS/CXXFLAGS

**Comment by danielsdeleo** [comment]
The second option seems like it should be fine. All the docs I've come across say `-O2` should be safe for all but the most insane software.

**Comment by scotthain** [comment]
Adding -O2 to the defaults should be fine, most of the places I've run into issues with it have explicit overrides already in their omnibus-software definition.

**Comment by curiositycasualty** [comment]
:+1: @danielsdeleo's comment. It could go into https://github.com/chef/omnibus/blob/master/lib/omnibus/software.rb for all the gcc platforms.

**Comment by lamont-granquist** [comment]
hmmmm

you might want to be a bit careful about -O2 with ruby on AIX.

i think that is no longer an issue since we're using xlc now, but gcc got all segfaulty when we used optimizations on ruby on AIX...

i think it should be there by default, but @scotthain will need to test a little closer on AIX after it goes in.

**Comment by lamont-granquist** [comment]
for zlib we never had optimizations all the way back to clojure omnibus:

https://github.com/chef/omnibus-software/blob/b6e893eac1c49124034ce2afe4376f978b156139/config/software/zlib.rb

**Comment by lamont-granquist** [comment]
ruby used to mostly use -O3 in .e.g:

https://github.com/chef/omnibus-software/blob/a5672d297af4d09c01c33d34785244b352193146/config/software/ruby.rb

that seems to have decayed over time.

i'm pretty sure the oversight of -O2 is mostly cargo cult -- and it looks like AIX won't pick up the defaults for ruby anyway...

i'm :+1:

**Comment by stevendanna** [comment]
https://github.com/chef/omnibus/pull/591/files

**Comment by scotthain** [comment]
@lamont-granquist on AIX and Solaris we override things 75%+ of the time simply because of the reasons you stated. Good thought though :)

**Comment by lamont-granquist** [comment]
#591 is merged
