### ISSUE TITLE
git_fetcher.rb code not compatible w/ git < 1.7.5

### ISSUE THREAD

**Issue by santisaez** [chef/omnibus#593]
Today, I realized that the packages I build using `git` fetcher has stopped working:

```bash
The following shell command exited with status 129:

    $ git checkout --detach 3bda6d772825e43f70541fa43c68e8c9f4ca3ebc -f -q

Output:

    (nothing)

Error:

    error: unknown option `detach'
usage: git checkout [options] <branch>
   or: git checkout [options] [<branch>] -- <file>...

    -q, --quiet           be quiet
    -b <new branch>       branch
    -l                    log for new branch
    -t, --track           track
    -2, --ours            stage
    -3, --theirs          stage
    -f, --force           force
    -m, --merge           merge
    --conflict <style>    conflict style (merge or diff3)
    -p, --patch           select hunks interactively
```

The following change seems the offender: https://github.com/chef/omnibus/commit/ac128923e448c24988d8e8471168a08a8dca7f4d.

`--detach` option is available since Git 1.7.5, see:

https://github.com/git/git/blob/master/Documentation/RelNotes/1.7.5.txt#L34-L35

I'm using `1.7.1`, the default version shipped with RHEL 6, so most probably more build environments without this recent Git version will be affected.

**Comment by ksubrama** [comment]
Oh that's annoying.  I used --detach because I was paranoid and didn't want the sha to be interpreted as anything else.  We can probably just drop --detach and it'll work as expected since the default is to checkout in detach when a sha is given.
