### ISSUE TITLE
Something is causing omnibus chef-client to fail on gem dependency

### ISSUE THREAD

**Issue by mikemackintosh** [chef/omnibus#610]
I just built a new version of our omnibus package on a brand new machine, which required all the dependencies and sources to be recached. Getting them was not an issue, but now after the package successfully builds, we can't run chef-client anymore.

`./projects/company-omnibus.rb`:
```
name          "CompanyOmnibus"
maintainer    "mike@buttsec.com"
homepage      "http://www.buttsec.com"
friendly_name "ButtSec"

# install Dir
install_dir   "/opt/omnibus/"

# Build stuff
build_version   "0.8.1"

# Override Versions
override :bundler,              version: "1.10.7.depsolverfix.0"
override :ruby,                   version: "2.1.7"
override :chef,                   version: "12.5.1"
override :openssl,              version: "1.0.1p"

dependency "chef"
dependency "preparation"
dependency "version-manifest"

# Packaging Stuff
exclude "**/.git"
exclude "**/bundler/git"
exclude "**/.bundler/git"
```

The package builds correctly, but when you try to run chef-client in the omnibus, it results in:

```
/opt/omnibus/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:247:in `to_specs': Could not find rack (= 1.5.5) amongst [appbundler-0.5.0, builder-3.2.2, bundler-1.10.7.depsolverfix.0, chef-12.5.1, chef-config-12.5.1, chef-config-12.5.0.alpha.1, chef-zero-4.4.2, coderay-1.1.0, diff-lcs-1.2.5, erubis-2.7.0, ffi-1.9.10, ffi-yajl-2.2.3, hashie-3.4.3, highline-1.7.8, ipaddress-0.8.2, libyajl2-1.2.0, method_source-0.8.2, mime-types-2.99, mixlib-authentication-1.4.0, mixlib-cli-1.5.0, mixlib-config-2.2.1, mixlib-log-1.6.0, mixlib-shellout-2.2.5, multi_json-1.11.2, net-scp-1.2.1, net-ssh-2.9.2, net-ssh-gateway-1.2.0, net-ssh-multi-1.2.1, net-telnet-0.1.1, net_http_unix-0.2.1, ohai-8.8.1, plist-3.1.0, pry-0.10.3, rack-1.6.4, rake-10.5.0, rspec-3.4.0, rspec-core-3.4.1, rspec-expectations-3.4.0, rspec-its-1.2.0, rspec-mocks-3.4.1, rspec-support-3.4.1, rspec_junit_formatter-0.2.3, ruby-shadow-2.5.0, serverspec-2.29.1, sfl-2.2, slop-3.6.0, specinfra-2.50.2, syslog-logger-1.6.8, systemu-2.6.5, uuidtools-2.1.5, wmi-lite-1.0.0] (Gem::LoadError)
	from opt/omnibus/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:256:in `to_spec'
	from opt/omnibus/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:1231:in `gem'
	from opt/omnibus/bin/chef-client:12:in `<main>'
```

Of course, looking in `chef-client` on line 12, you see the pinned version of `rack` at `= 1.5.5`, but it didnt look like it was ever installed. After running `/opt/omnibus/embedded/bin/gem install rack -v 1.5.5` , `chef-client` started to work again.

Happens both on OS X and Debian built packages, along with both version of `omnibus 4.1` and `5.0`

**Less-Interactive Fix:**

I copied the `software/chef.rb` config, and added:

```
  auxiliary_gems['rack'] = '= 1.5.5'
```

Rebuilt and installed, works as expected.

**Comment by lamont-granquist** [comment]
could be your version of bundler:

https://github.com/chef/chef/blob/master/omnibus/config/projects/chef.rb#L35

we're not seeing that internally, so its likely some delta between how you're trying to build chef-client and how we are.

you might look at the angrychef definition for how to 'inherit' and override from our definition:

https://github.com/chef/chef/blob/master/omnibus/config/projects/angrychef.rb

**Comment by lamont-granquist** [comment]
and this is certainly the wrong project to report this into, since its not going to be a bug in the omnibus packager itself...
