### ISSUE TITLE
How to explicitly set version for git sources?

### ISSUE THREAD

**Issue by mgrobelin** [chef/omnibus#620]
Hi chefs,

in a libgpg-error software definition I used to checkout sources from git by a tag. This tag is called 'libgpg-error-1.21'.

While building it prints this warning:
 `[Software: libgpg-error] W | Version libgpg-error-1.21 for software libgpg-error was not parseable. Comparison methods such as #satisfies? will not be available for this version.`

Is there a way to threat this version as '1.21'?

**Comment by schisamo** [comment]
I believe that warning should not affect anything. You just won't be able to use the software def's version in things like:
https://github.com/chef/omnibus-software/blob/56f4933c94cfcb85be7b3564ccab280769d90d12/config/software/libzmq.rb#L48

**Comment by mgrobelin** [comment]
Yes, it does not really hurt, but I want to use that `.satifies?' method and some other magick, especially when using git-sources.

Background: 
I currently have ~100 software def's in my project. 10 to 20 are using git with unusable default_version identifier, e.g.:
- master
- 2016.01.20
- 20120601-3.0
- 8d
- coollib-1.1.5
- cooltool-5.5.47-rel7
- coolerlib-v0.3.0
- ruby-windows
- V_7_1_P2

What I want to achieve, is to be able to build my things with current (already released), but also upcoming (not yet released, or even developed) dependencies. Something like this, may reflect the idea:

```
name 'mylib'

# until 1.1.6 is released, checkout master branch, but treat internally as version 1.1.6
default_version = if ENV['build_target'] == 'upcoming_release'
                        'master'
                    else
                        'mylib-1.1.5'
                    end

source git: 'https://git/mylib'
source treat_version: '1.1.6' if ENV['build_target'] == 'upcoming_release'

if version.satisfies?('<= 1.1.5')
  # apply patches and other magick
end

build do 
  configure_args = [
    '--mylib-standard-arg',
  ]

  configure_args.push('--mylib-new-arg') if version.satisfies?('> 1.1.5')
```

What do you think?

**Comment by schisamo** [comment]
@mgrobelin You want to use a project override for this type of thing...for example this override:
https://github.com/chef/chef-dk/blob/master/omnibus/config/projects/chefdk.rb#L36

would make the `chef` software def build a specific version (instead of the default of HEAD master):
https://github.com/chef/omnibus-software/blob/master/config/software/chef.rb#L17

**Comment by mgrobelin** [comment]
@schisamo I already spotted that version override feature, but it does not help for my usecase. 

My origin request is indeed exotic, as I could achieve the wanted behavoir with git and having some branches.

But talking about overrides, I want to feedback this as follows:

While evaluating omnibus I found myself more than once,  duplicating software def's only to have small diverges by configure-/make-statements or even just a minor difference in environment variables.

Take any typical server-client software - e.g. postgresql or openssh - and build a client-package and a server-package. 

Within my big project, I achieved this by having such a structure:

├── projects
│   ├── client.rb
│   └── server.rb
├── software
│   ├── server-postgresql.rb
│   ├── client-postgresql.rb


 ... here server-postgresql.rb and client-postgresql.rb are pretty equal, except of the configure and make arguments.

This feels like duplication to me, because what I thought to do is using one generic postgresql software def and overrides in my projects like this (dummy code):

client.rb: 
```
dependency 'postgresql'
override :postgresql, configure: [ "--client-only-args", "--foo" ]
override :postgresql, make: "-j #{workers} src/bin install"
override :postgresql, make: "-j #{workers} src/include install"
override :postgresql, make: "-j #{workers} src/interfaces install"
override :postgresql, make: "-j #{workers} doc install" 
```

server.rb: 
```
dependency 'postgresql'
override :postgresql, configure: [ "--server-only-args", "--bar" ]
override :postgresql, make: "-j #{workers} world install" 
```

Having more powerful overrides, would simplify my software def's and their maintenance. 

Somewhere in github I already read about some plans to enhance this, but I can't find the "bug" anymore.

**Comment by lamont-granquist** [comment]
I think I'm solidly against this.  The feature request is equivalent to asking for an inheretance-like mechanism where the "subclass" can monkeypatch the upstream resource.  But that implicitly creates a public API which may break due to the normal course of maintenance of the upstream software definition, with the maintainer of that config having zero visibility into how consumers may have tweaked the config.  As a result the best practice is fork-and-change, see also the omnibus-software statement [here](https://blog.chef.io/omnibus-a-look-forward/), or look into using habitat.
