### ISSUE TITLE
Disable dist_tag configuration

### ISSUE THREAD

**Issue by pradeepchhetri** [chef/omnibus#624]
Hello,

I see that this commit https://github.com/chef/omnibus/pull/424/files adds the dist tag to package name and spec file. Is there any way i can turn this off. If no, will you be interested in accepting it as a pull request. 

My use case:
I want to build one package for all rpm based distro releases. Hence i don't want to append the dist tag with package name.

Thank you.

**Comment by pradeepchhetri** [comment]
@schisamo Any suggestions about how to build without dist tag in the package name.

**Comment by yzl** [comment]
@pradeepchhetri You can ignore the dist tag by [overriding the default spec file locally](https://github.com/chef/omnibus/blob/master/lib/omnibus/packagers/base.rb#L184-L198).

**Comment by pradeepchhetri** [comment]
@yzl Thank you for the help. I changed the spec file to not to append the `dist_tag` but now the validation step is failing saying

```
Could not locate or access the package at the given path:
    /var/cache/omnibus/pkg/barricade-0.5.0-1.el6.x86_64.rpm
```

It is still looking for the filename with `dist_tag` but now the file getting created is without one. I guess it is because of `package_name`. Is there any way i can override this.

https://github.com/chef/omnibus/blob/master/lib/omnibus/packagers/rpm.rb#L212-L214

**Comment by pradeepchhetri** [comment]
@yzl I am stuck at this for a very long time. Any quick will be very appreciated. Thank you.

**Comment by schisamo** [comment]
@pradeepchhetri I'm sorry the suggested workarounds are not working for you. I think the only way to accomplish what you are hoping to do is making the `dist_tag` optional. You could probably promote the current `dist_tag` method to a full blown DSL method on `Omnibus::Packager::RPM`. The default value should be the current value of `".#{Omnibus::Metadata.platform_shortname}#{Omnibus::Metadata.platform_version}"`. You could then configure a value of false in your project def like this:

```ruby
package :rpm do
  dist_tag false
end
```

Anywhere the dist_tag method is called in `Omnibus::Packager::RPM` would then need have some branching logic like:

```ruby
def package_name
  if dist_tag
    "#{safe_base_package_name}-#{safe_version}-#{safe_build_iteration}#{dist_tag}.#{safe_architecture}.rpm"
  else
    "#{safe_base_package_name}-#{safe_version}-#{safe_build_iteration.#{safe_architecture}.rpm"
  end
end
```

We'll obviously want some good unit test coverage for these changes. Hope that helps!

**Comment by pradeepchhetri** [comment]
Hi @schisamo, I got what you are saying. I will try implementing it and add unit tests and will open a pull request accordingly. Thank you for the help.

**Comment by pradeepchhetri** [comment]
Opened this pull request: https://github.com/chef/omnibus/pull/634
