### ISSUE TITLE
libc6 as software dependency

### ISSUE THREAD

**Issue by pradeepchhetri** [chef/omnibus#625]
I am getting the following error while starting the service in Debian Squeeze and Wheezy:

```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /opt/gandalf/embedded/lib/libpython2.7.so.1.0)
```

This is because the version of default `libc6` is 2.11(squeeze) and 2.13(wheezy) while the minimum required version is 2.15. Can i add it as a software dependency for my project.

Thank you.

**Comment by schisamo** [comment]
glibc versions are forward compatible. You need to build your project on the oldest version of Debian you hope to support. In this case if you build the project on `squeeze` (6.0) it will also work on `wheezy` (7.0) and `jessie` (8.0).
