### ISSUE TITLE
Licensing fails when software is restored from GitCache

### ISSUE THREAD

**Issue by jkeiser** [chef/omnibus#696]
### Description

When a software definition is restored from GitCache, and its corresponding build directory does not exist, licensing fails to find the file.

### Omnibus Version

`master`

### Platform Version

All OS's Chef builds on.

### Replication Case

This will happen anytime /var/omnibus/cache/src is empty; but one specific case where this can happen even without deleting the directory:

1. I build my project including ruby-2.1.8. /var/omnibus/cache/src/ruby/ruby-2.1.8 exists, and the licensing stuff works. ruby-2.1.8 output is in GitCache.
2. I build my project with ruby-2.2.5. GitCache doesn’t restore it, it downloads /var/omnibus/cache/src/ruby/ruby-2.2.5, and FAILS to build (for external reasons). Nothing is output to GitCache.
3. I try ruby-2.1.8 again. It restores everything from GitCache, but /var/omnibus/cache/src/ruby/ruby-2.1.8 is not there. Licensing fails.

Licensing fails because it looks for the license files in that dir, but it didn’t need to download or build the source so that dir does not exist

### Build Output

```
              [Licensing] W | 2016-07-28T21:45:05+00:00 | License file '/var/cache/omnibus/src/ruby/ruby-2.1.8/BSDL' does not exist for software 'ruby'.
              [Licensing] W | 2016-07-28T21:45:05+00:00 | License file '/var/cache/omnibus/src/ruby/ruby-2.1.8/COPYING' does not exist for software 'ruby'.
              [Licensing] W | 2016-07-28T21:45:05+00:00 | License file '/var/cache/omnibus/src/ruby/ruby-2.1.8/LEGAL' does not exist for software 'ruby'.
Encountered error(s) with project's licensing information.
Failing the build because :fatal_licensing_warnings is set in the configuration.
Error(s):

    License file '/var/cache/omnibus/src/ruby/ruby-2.1.8/BSDL' does not exist for software 'ruby'.
    License file '/var/cache/omnibus/src/ruby/ruby-2.1.8/COPYING' does not exist for software 'ruby'.
    License file '/var/cache/omnibus/src/ruby/ruby-2.1.8/LEGAL' does not exist for software 'ruby'.
```

--------------------------------------------------
/cc @chef/omnibus-maintainers

**Comment by danielsdeleo** [comment]
I'm working on this as it's closely related to some work we need to do for transitive dependency license collection.
