### ISSUE TITLE
Omnibus 5.5.0's appx.rb is halting automation with the current use of the `pack_command`

### ISSUE THREAD

**Issue by balmyBanzai** [chef/omnibus#707]
### Description

Omnibus 5.5.0's appx.rb is halting automation with the current use of the `pack_command` when prompted to overwrite

### Omnibus Version

5.5.0

### Ruby Version

2.2.5p319

### Platform Version

Windows 8.1

### Replication Case

One of our jenkins jobs was getting held up indefinitely, and after investigating verbose logs, the place it was halting was at:

`14:52:14          [Packager::APPX] I | 2016-08-24T14:58:32-07:00 | $ makeappx.exe pack /d "C:\FolderToPackage" /p C:\omnibus-ruby\pkg\InstallerName-0.0.0-1.appx`

When running this manually via CMD, I saw the prompt to overwrite -- this of course is halting automation.

### Build Output

N/A

### Workaround

I went into the local installation of ruby 2.2 and edited Omnibus's appx.rb to add the `/o` switch

### Feedback 

I'm not a ruby dev, just doing the build-engineer thing. Is there a way I can communicate to my devs that they need to do something to enable this overwrite behavior at the makeappx call level? It doesn't seem like there's currently support for it, but I don't know much of anything about ruby or omnibus, just observing the source of appx.rb

If there isn't a way to do this now, should I run local updates on all the Jenkins nodes? I'd rather not add an extra layer of obfuscation to understanding the build requirements of omnibus installers, so some sort of patch or bug fix would be appreciated if the dev can't overcome this behavior higher up the stack.

--------------------------------------------------
/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

**Comment by mwrock** [comment]
I will submit a pr to fix
