### ISSUE TITLE
Fails to build ruby on windows

### ISSUE THREAD

**Issue by jonathanmorley** [chef/omnibus#719]
### Description

Using the ruby software from chef/omnibus-software causes the build to fail when run on Windows
### Omnibus Version

5.0.5
### Platform Version

Windows Server 2016 (@mwrock's vagrant box)
### Replication Case

```
git clone https://github.com/jonathanmorley/ruby-omnibus-test.git
cd ruby-omnibus-test
kitchen test # wait about an hour
```
### Build Output

```
           C:/omnibus-ruby/src/ruby/ruby-2.3.1/lib/yaml.rb:5:in `<top (required)>':
           It seems your ruby installation is missing psych (for YAML output).
           To eliminate this warning, please install libyaml and reinstall your ruby.
           C:/omnibus-ruby/src/ruby/ruby-2.3.1/lib/rubygems/core_ext/kernel_require.rb:55:in `require': 126: The specified module could not be found.   - C:/omnibus-ruby/src/ruby/ruby-2.3.1/.ext/i386
-mingw32/psych.so (LoadError)
```
---

/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

**Comment by jonathanmorley** [comment]
This is resolved with the following Gemfile:

**Comment by mwrock** [comment]
yes @jonathanmorley we (chef) actually run derrivitive branches off of those same ones. There is an effort under way now to get all that craziness into the master branches.
