### ISSUE TITLE
macosx broken with 5.5.0 release

### ISSUE THREAD

**Issue by dhoer** [chef/omnibus#724]
### Description

Omnibus no longer works on macosx versions.  See https://travis-ci.org/dhoer/chef-java_se/builds/168828310

### Omnibus Version

5.5.0, no mac builds have functioned properly since August travis ci.  

### Platform Version

Mac osx xcode 8, 7.4, and 6.3 

### Replication Case

Run any macosx build on travis-ci. None of the mac builds run properly.

### Build Output

https://travis-ci.org/dhoer/chef-java_se/builds/168828310

--------------------------------------------------
/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

**Comment by scotthain** [comment]
Hi @dhoer - from these logs it looks like this may not be an omnibus specific issue, as the chef-client run didn't complete:
```
       /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'ohai' (= 8.20.0) - did find: [ohai-8.21.0] (Gem::MissingSpecVersionError)
       Checked in 'GEM_PATH=/Users/travis/.rvm/gems/ruby-2.2.5:/Users/travis/.rvm/gems/ruby-2.2.5@global', execute `gem env` for more information
```

I believe that the latest version of chef-client that is running here (12.15.19) needs ruby 2.3, not 2.2 - I'd try updating that to start with. If that doesn't work I'd recommend opening an issue against the https://github.com/chef/chef repo, as it didn't even get to testing out omnibus itself.

**Comment by tas50** [comment]
@dhoer I took a quick peak at your travis config and noticed you had RVM setup for ruby 2.2. Can you try bumping that to 2.3.1 to see if that resolves things. We had issues with rack dropping support for Ruby < 2.2.2 several months ago which caused us to start setting similar minimum ruby support. The RVM aliases in Travis don't get updated so 2.2 doesn't give you 2.2.5 like you might think. If you want to stick with the 2.2 branch specify 2.2.5 to get the latest there.

**Comment by dhoer** [comment]
I did try 2.3 ruby on chrome before writing this up: https://travis-ci.org/dhoer/chef-chrome/builds/167251568.  Looks like I need to open an issue with chef.
