### ISSUE TITLE
Add ability to keep specs / srpms

### ISSUE THREAD

**Issue by brk3** [chef/omnibus#760]
### Description

It would be useful to have omnibus produce spec files and srpms alongside the current pkg assets. Something like https://github.com/brk3/omnibus/commit/7bde4c3e6ddd98107fd62cf5904ebf7d67473605 does the trick, but needs further work to make it robust enough for a pull request.

**Comment by srenatus** [comment]
@brk3 I'm not sure I understand this. From what I understand, SRPMs contain _the sources_ required to re-build the package (when combined with the spec file). For a typical omnibus package, that would be _very much_, I suppose. What's your use case, if I may ask?

Also, I might not understand the interplay between (s)rpm and spec file here. There's nothing in the omnibus-generated spec indicating how to _compile the software_, since this is what the software definitions do. Could you elaborate what you're trying to achieve? 😃

**Comment by brk3** [comment]
@srenatus Typically a srpm contains a source tarball and also a spec file that has steps to build and package it. It's common for rpm distros to have a repo of srpms for each rpm available, to allow users to easily rebuild them if desired. This is my use case - we have continuous integration set up to build rpms from srpms, setting up new jobs to run omnibus for the select packages that use it was undesirable.

It's been a while I looked at this but from what I could tell, under the hood omnibus is essentially creating a specfile and then calling standard rpmbuild commands to build it (for the rpm case). Currently the arguments are `-bb` which means 'produce binary packages only', where as modifying it to something like `-ba` as in my patch will also produce srpms. What I'm not sure is how well these srpms can be rebuilt outside the omnibus environment, this is something that would require more testing.

Unfortunately right now I don't have the resources to work on this, so can close out for now. Hopefully this can serve as a starting point if anyone else is interested in this in the future.

Thanks!
-Paul

**Comment by srenatus** [comment]
@brk3 thanks for taking the time to wrap this up with information 😃 

> It's been a while I looked at this but from what I could tell, under the hood omnibus is essentially creating a specfile and then calling standard rpmbuild commands to build it (for the rpm case). 

This is true, but it might deviate from the "ordinary" RPM build process here -- when omnibus calls rpmbuild, it *has already built* all the binary artifacts, and it's only using rpmbuild to wrap these up with some metadata and turn that into an RPM package. So, I doubt that the resulting SRPM would be "a true source RPM" in any way -- however, in your situation, I might be good enough to look like an SRPM.
