### ISSUE TITLE
`*.appx` packages are missing architecture in the package name

### ISSUE THREAD

**Issue by schisamo** [chef/omnibus#762]
The package that `Omnibus::Packager::APPX` generates should contain the architecture in the name. This will match the naming behavior of the rest of Omnibus's packagers.

The fix should be as easy as changing [`Omnibus::Packager::APPX#package_name `](https://github.com/chef/omnibus/blob/76d907f4fe92a28c5f7ab11779341e1d773c358d/lib/omnibus/packagers/appx.rb#L55) from:

```ruby
def package_name
  "#{project.package_name}-#{project.build_version}-#{project.build_iteration}.appx"
end
```

to:

```ruby
def package_name
  "#{project.package_name}-#{project.build_version}-#{project.build_iteration}-#{Config.windows_arch}.appx"
end
```

This will match the behavior we use for [`Omnibus::Packager::MSI`](https://github.com/chef/omnibus/blob/76d907f4fe92a28c5f7ab11779341e1d773c358d/lib/omnibus/packagers/msi.rb#L268-L270).

**Comment by srenatus** [comment]
#764 fixed this :+1:
