### ISSUE TITLE
Downloading install.ps1 over HTTPS using PowerShell script failing with SSL certificate issue

### ISSUE THREAD

**Issue by adhodgson1** [chef/omnibus#773]
### Description
Running the command:
iex (irm https://omnitruck.chef.io/install.ps1); Install-Project -Project chefdk -channel stable

Currently causes an error due to the certificate failing validation.  I believe this is because the cert being returned is from Fastly, and doesn't match omnibus.chef.io.  This has caused some AppVeyor build jobs we use and some instances to fail to come up properly that uses this script.

### Omnibus Version

Using current version of the PowerShell install script.

### Platform Version

Windows 2012 R2 and Windows 8.1.

### Replication Case

Run the command:

iex (irm https://omnitruck.chef.io/install.ps1); Install-Project -Project chefdk -channel stable

From a Powershell prompt or from a CI server that uses this command to install Chef.

### Build Output

The relevant output of the Omnibus build or a link to a gist of the entire build, if there is one.

At line:1 char:6
+ iex (irm https://omnitruck.chef.io/install.ps1); Install-Project -Pro ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

--------------------------------------------------
/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

**Comment by schisamo** [comment]
@adhodgson1 I believe you meant to open this issue over in https://github.com/chef/omnitruck. I'm closing this issue but feel free to recreate it in the proper repo.
