### ISSUE TITLE
Specific Revision or Tag with Git

### ISSUE THREAD

**Issue by gcaracausi** [chef/omnibus#824]
### Description

I need for a software component to download a specific tag or revision from Git. 
Is it possible ? 

Something like:

`source git: <my_url>, <revision|tag>`

### Omnibus Version

5.6.8

### Platform Version

Ubuntu 16.04

--------------------------------------------------

**Comment by scotthain** [comment]
If the version you are looking for is static, you can specify:
```
default_version "<rev|tag>"
source git: "<url>"
```

There are also numerous examples here you can reference! https://github.com/chef/omnibus-software/tree/master/config/software

**Comment by gcaracausi** [comment]
I tried with the branch name and it didn't work. 
It is working with the complete revision number. 
Thanks
