### ISSUE TITLE
Exclude overmatches directory globs

### ISSUE THREAD

**Issue by richardc** [chef/omnibus#833]
### Description

Exclude seems to overmatch directory levels

### Omnibus Version

v5.6.10

### Platform Version

CentOS 7.  x86_64

### Replication Case

Adding the following to a project that installs many rubygems:

```ruby
exclude 'embedded/lib/ruby/gems/*/cache'
```

Excluded not only the intended `embedded/lib/ruby/gems/2.3.0/cache` directory, but also `embedded/lib/ruby/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cache` directory, which was alarming and broke the resulting package.

My expectation would be that I'd need to specify `**` to get that behaviour:

```ruby
exclude 'embedded/lib/ruby/gems/**/cache'
```

Looking at the code I think that if [the call to `File.fnmatch?()` in the exclusion matching code](https://github.com/chef/omnibus/blob/7f3652f85986ba24d681493bf2968326bfc2de46/lib/omnibus/file_syncer.rb#L65) specified additionally `File::FNM_PATHNAME` then I'd get the behaviour I expect.

Is my expectation fair?  If so I'm happy to provide a patch.

**Comment by glensc** [comment]
@richardc never link to a branch, use permalinks!

you know `y` hotkey, right?

**Comment by richardc** [comment]
@glensc I didn't, and I'll probably forget it immediately.

Will update the link
