### ISSUE TITLE
Packages not published in 6.0.2

### ISSUE THREAD

**Issue by jmartin-r7** [chef/omnibus#877]
### Description

Packages for tagged versions > 6.0.1 have not published to rubygems.

### Omnibus Version
\> 6.0.1

### Platform Version

ALL

### Replication Case

https://rubygems.org/gems/omnibus

### Build Output

N/A

**Comment by pkleanthous** [comment]
Hi, 

Any updates on this? 

I can confirm that we stack at `omnibus Version 6.0.1` in rubygems.org

**Comment by robbkidd** [comment]
v6.0.24 (the latest version as of this comment) just pushed to RubyGems.
