### ISSUE TITLE
Use specific version of Chef Infra Client

### ISSUE THREAD

**Issue by GoelJatin** [chef/omnibus#893]
### Description

Hi Team,

We're trying to use the `14.5.33` version of Chef Infra client, but it is always using the latest one - `15.1.xx`.

I tried looking up the docs to get more info on this, but couldn't find any.

Any help would be much appreciated!!!

### Omnibus Version

`v6.0.1`

### Platform Version

Ubuntu 16

--------------------------------------------------

**Comment by lamont-granquist** [comment]
This repo does not have a dependency on the chef gem so this issue cannot be reproduced.

**Comment by GoelJatin** [comment]
Hi @lamont-granquist , we figured out the problem. Even though we specified what version to use in the Gemfile there was another gem which had an open-ended dependency on Chef and it was downloading the latest version of the Chef gem.

We thought it was omnibus which was somehow interfering with the versions here. Apologies for the in-convenience.
