### ISSUE TITLE
chef-sugar yanked breaking omnibus

### ISSUE THREAD

**Issue by truthbk** [chef/omnibus#901]
### Description

Seth Vargo's `chef-sugar` has been yanked from rubygems.org and his repository archived: https://github.com/sethvargo/chef-sugar.

As a consequence, this has broken omnibus due to its dependency with it. I believe all versions, certainly `6.x` and `5.5.x` are affected. 

### Omnibus Version

`5.5.0`

### Platform Version

All platforms affected.

### Replication Case

Installation of the `omnibus` gem will fail. 

### Build Output
```
Bundler could not find compatible versions for gem "chef-sugar":
  In Gemfile:
    omnibus was resolved to 5.5.0, which depends on
      chef-sugar (~> 3.3)

Could not find gem 'chef-sugar (~> 3.3)', which is required by gem 'omnibus', in any of the sources.
```

--------------------------------------------------

**Comment by btm** [comment]
Fixed in https://github.com/chef/omnibus/pull/903, released as v6.1.4
