### ISSUE TITLE
centos8 rpms include build-id directory

### ISSUE THREAD

**Issue by twk3** [chef/omnibus#933]
### Description

When building an rpm package on centos8, with its newer rpmbuild, the package ends up including files in `/usr/lib/.build-id`

Similar issue logged with fpm: https://github.com/jordansissel/fpm/issues/1503

and sounds like it can be disabled for rpmbuild 

```
define "_build_id_links none"
```

### Omnibus Version

v5.6.12

### Platform Version

CentOS 8

**Comment by haidangwa** [comment]
I ran into this today trying to install Supermarket 4.1.28 onto a RHEL 8 Test Kitchen instance.

```
Error: Transaction test error:
  file /usr/lib/.build-id/ff/ed13d7b76a61d3dbc3744d5f4557d1dfca2ed3 from install of supermarket-4.1.28-1.el8.x86_64 conflicts with file from package chef-16.17.18-1.el8.x86_64
```

I got this error with 4.0.21, as well:

```
Error: Transaction test error:
  file /usr/lib/.build-id/ff/ed13d7b76a61d3dbc3744d5f4557d1dfca2ed3 from install of supermarket-4.0.21-1.el8.x86_64 conflicts with file from package chef-16.17.18-1.el8.x86_64
```

**Comment by tas50** [comment]
This has been resolved by https://github.com/chef/omnibus/commit/a7e8f7a79b97376a27c9d0453a25e6694062664c
