### ISSUE TITLE
Releases are not publishing to rubygems.org

### ISSUE THREAD

**Issue by jmartin-r7** [chef/omnibus#946]
### Description

Releases are not publishing to rubygems.org.  The last published gem for `omnibus` is `6.1.9` released Nov. 1, 2019.  There are known issues in `6.1.9` requiring projects that want an updated version to pin a github tag to get current versions.

### Omnibus Version

6.1.10 and newer

### Platform Version

N/A

### Replication Case

`bundle update` a project dependent on `gem 'omnibus'` from a public environment.

See: https://rubygems.org/gems/omnibus

**Comment by tas50** [comment]
@jmartin-r7 I pushed 7.0.12 up to Rubygems. It's not something we really think about doing much at Chef since we consume the gem from rubygems in all our projects. Let us know if you need it pushed up again in the future.
